### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by pudkeaayush** [jmiller656/DiscoGAN-Tensorflow#3]
Hello,
I am getting the following error while running:

File "main.py", line 5, in <module>
    g = utils.generator(a)
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/utils.py", line 135, in generator
    conv_t_1 = conv_layer_t(conv_4,[4,4,im_size,int(conv_4.get_shape()[-1])],[im_size],[tf.shape(x)[0],im_size/8,im_size/8,im_size],activation=lrelu,batch_norm=g_bn3,name="g_deconv_1",reuse=reuse)
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/utils.py", line 75, in conv_layer_t
    h = conv2d_t(x,w,shape)+b
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/utils.py", line 29, in conv2d_t
    return tf.nn.conv2d_transpose(x,w,shape,strides=[1,stride,stride,1],padding=padding)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1024, in conv2d_transpose
    output_shape_ = ops.convert_to_tensor(output_shape, name="output_shape")
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 919, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 881, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 374, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 8.0 of type 'float' instead.

Could you help to provide a fix? Seems we need to typecast specifically

**Comment by jmiller656** [comment]
Hey, thanks for pointing this out. I'm not sure I've fixed your issue, but I realized that main.py was not up to date. Just made a quick change. Could you try pulling and running it again. 

Also, could you tell me what version of tensorflow you are running?

**Comment by pudkeaayush** [comment]
Hey there,
I am using version 1.2.0.

I ran with the new changes and got another error.  This is the output:

Building Model
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    network = DiscoGAN()
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/discoGAN.py", line 21, in __init__
    self.g_ab = utils.generator(self.x_a,name="gen_AB",im_size=im_size)
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/utils.py", line 135, in generator
    conv_t_1 = conv_layer_t(conv_4,[4,4,im_size,int(conv_4.get_shape()[-1])],[im_size],[tf.shape(x)[0],im_size/8,im_size/8,im_size],activation=lrelu,batch_norm=g_bn3,name="g_deconv_1",reuse=reuse)
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/utils.py", line 75, in conv_layer_t
    h = conv2d_t(x,w,shape)+b
  File "/Users/haosun/Raju/DiscoGAN-Tensorflow-master/utils.py", line 29, in conv2d_t
    return tf.nn.conv2d_transpose(x,w,shape,strides=[1,stride,stride,1],padding=padding)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 1024, in conv2d_transpose
    output_shape_ = ops.convert_to_tensor(output_shape, name="output_shape")
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 676, in convert_to_tensor
    as_ref=False)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 741, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 919, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 881, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 102, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 374, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/Users/haosun/Raju/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 302, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 8.0 of type 'float' instead.

I guess some typecasting issue is occuring.

**Comment by jmiller656** [comment]
My bad, you are correct. Looks like I found the issue. Thanks again for pointing this out!
I believe I've fixed the issue now. Could you please try again?

**Comment by pudkeaayush** [comment]
I am still getting the previous issue after taking the updated code only. Are you sure it is fixed? Is it working for you? I get the same error with the same logs

**Comment by jmiller656** [comment]
I'm currently working in a different version of both tensorflow and python and have never experienced this error. Updating tf and installing python 3.6 right now. I'll keep you posted

**Comment by jmiller656** [comment]
If you'd like to try, the code is running without error for me on python 2.7 and tf version 1.0

**Comment by jmiller656** [comment]
Was able to reproduce the error with python3.6.
Fixing now

**Comment by jmiller656** [comment]
@pudkeaayush I've just made some changes and currently have it running in the newest version of tf on python3.6 

Please try it out and tell me if it fixes your problem.

**Comment by pudkeaayush** [comment]
Hey,
I tried. It works like charm! Thank you so much. I just wanted to ask you how I can use my own custom dataset instead of celebA now? Say I have two different image sets A and B , how should I make the list_attribute file? Will I need to do something else in the code to generate new images from A and B?

Regards

**Comment by jmiller656** [comment]
Awesome! 
I've been trying to think of good ways to abstract the data feeding part of this but haven't thought of anything particularly great yet. 

For now, the best way to do this is to (sadly) change the get_batches() function in data.py

Essentially, this is used inside the training loop in the DiscoGAN object I created. DiscoGAN will ask for a batch of images of a certain size, and from a certain domain. From there, the get_batches() function will take a random group of images from that domain, load them into an array, preprocess them, and then return them. 

If you would like to do the same, here's how I'd probably go about it:

Let's assume your images are in two directories, A and B, each containing images for their respective domains.

```
#Here are the changes I'd make to get_batches
def get_batches(size,domain):
    #Get list of images to select from based on domain
    if domain=='a':
        samples = os.listdir("A")
        dirname = "A/"
    else:
        samples = os.listdir("B")
        dirname = "B/"
    #Get sample indices to include in image batch
    indices = random.sample(range(0,len(samples)),size)
    images = []
    for i in indices:
        #Read in image to add to batch
        img = scipy.misc.imread(dirname+i)
        #Preprocess image (this is done using code already inside data.py)
        img = preprocess(img)
        #Add image to batch
        images.append(img)
    return np.asarray(images)
```

I haven't tested this code and kinda just wrote it on the fly, but hopefully it gives a general idea as to how to do what you'd like until I figure out a decent way to abstract it out.

**Comment by pudkeaayush** [comment]
Thanks a ton! That is wonderful. So there would be no requirement of the list attribute file in that case or would it? Can we completely ignore the attribute file?

**Comment by jmiller656** [comment]
Correct! No attribute list is required. I only used it because it was the best way of separating images into different domains from celeba. Glad I could help!

**Comment by pudkeaayush** [comment]
Great! I am able to run with different datasets now. I will experiment with a couple of datasets and see what kind of results I can get.
You have helped immensely. Thank you again for the help :) Much appreciated.
